<?php

namespace App\Orchid\Layouts\Product;

use App\Models\Price;
use App\Models\Seller;
use Orchid\Screen\Fields\Input;
use Orchid\Screen\Fields\Relation;
use Orchid\Screen\Repository;
use Orchid\Support\Facades\Layout;
use Orchid\Screen\Layouts\Listener;

class ProductSellerPriceListener extends Listener
{
    /**
     * List of field names for which values will be listened.
     *
     * @var string[]
     */
    protected $targets = ['sellers'];

    /**
     * What screen method should be called
     * as a source for an asynchronous request.
     *
     * The name of the method must
     * begin with the prefix "async"
     *
     * @var string
     */
    protected $asyncMethod = 'asyncAddPriceField';

    /**
     * @return Layout[]
     */
    protected function layouts(): array
    {
        return [
            Layout::rows([
                Relation::make('product.sellers')
                    ->title(__('admin.products.sellers'))
                    ->fromModel(Seller::class, 'name')
                    ->multiple(),

                Input::make('sum')
                    ->readonly()
                    ->canSee($this->query->has('sum')),
            ]),
        ];
    }

    public function build(Repository $repository)
    {
        $parent = parent::build($repository);
        return $parent; // TODO: Change the autogenerated stub
    }
}
